version: "3.8"
services:
  recommendation_container:
    container_name: recommendation_container
    build: ./
    command: ./wait-for-db.sh ./recommendation_service "migrate"
    environment:
      - POSTGRES_HOST=go_shop_postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=5432
      # - KAFKA_BROKER=kafka:9092
    networks:
      - shopongo_default
    ports:
      - "8086:8086"

networks:
  shopongo_default:
    external: true